version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w0l6r4w0
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodenew .
      - docker tag nodenew:latest public.ecr.aws/w0l6r4w0/nodenew:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/w0l6r4w0/nodenew:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-app","imageUri":"public.ecr.aws/w0l6r4w0/nodenew:latest"}]' public.ecr.aws/w0l6r4w0/nodenew:latest > imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json 
